services:
  - type: web
    name: find-backend
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: FRONT_URL
        sync: false
      - key: BACK_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: MONGO_DSN
        sync: false
      - key: MONGO_DATABASE
        sync: false
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        sync: false
      - key: MAIL_ADMIN_ADDRESS
        sync: false
      - key: FEDAPAY_PUBLIC_KEY
        sync: false
      - key: FEDAPAY_SECRET_KEY
        sync: false
      - key: FEDAPAY_ENV
        sync: false
      - key: FEDAPAY_WEBHOOK_SECRET
        sync: false
